#!/usr/bin/env bash
set -euo pipefail

if [[ "$#" -ne 4 ]]; then
  echo "usage: $0 <registry-prefix> <version> <digest-directory> <output-file>" >&2
  exit 2
fi

registry_prefix="${1%/}"
release_version="${2#v}"
digest_directory="$3"
output_file="$4"

read_digest() {
  local image_name="$1"
  local digest_file="${digest_directory}/${image_name}.digest"
  if [[ ! -f "${digest_file}" ]]; then
    echo "missing release digest: ${digest_file}" >&2
    exit 3
  fi
  local digest
  digest="$(tr -d '[:space:]' <"${digest_file}")"
  if [[ ! "${digest}" =~ ^sha256:[0-9a-f]{64}$ ]]; then
    echo "invalid release digest for ${image_name}" >&2
    exit 4
  fi
  printf '%s' "${digest}"
}

backend_digest="$(read_digest kubeoncall-backend)"
console_digest="$(read_digest kubeoncall-console)"
controller_digest="$(read_digest kubeoncall-sandbox-controller)"
python_digest="$(read_digest kubeoncall-sandbox-generated-python)"
shell_digest="$(read_digest kubeoncall-sandbox-generated-posix-shell)"
manifest_digest="$(read_digest kubeoncall-sandbox-manifest-validation)"

cat >"${output_file}" <<EOF
# Generated by the KubeOnCall release workflow for ${release_version}.
# All executable images are pinned to the multi-platform manifest digest.
image:
  repository: ${registry_prefix}/kubeoncall-backend
  tag: ${release_version}
  digest: ${backend_digest}

console:
  image:
    repository: ${registry_prefix}/kubeoncall-console
    tag: ${release_version}
    digest: ${console_digest}

sandboxController:
  enabled: true
  image:
    repository: ${registry_prefix}/kubeoncall-sandbox-controller
    tag: ${release_version}
    digest: ${controller_digest}

config:
  sandboxEnabled: true
  sandboxFixedDiagnostic: false
  sandboxGeneratedCode: true
  sandboxManifestValidation: true
  sandboxRemediationSimulation: false
  sandboxAgentAutoRouteEnabled: false

sandboxTools:
  catalog:
    enabled: true
  tools:
    - id: generated-python
      version: v1
      mode: GENERATED_CODE
      enabled: true
      image:
        repository: ${registry_prefix}/kubeoncall-sandbox-generated-python
        digest: ${python_digest}
      entrypoint: /usr/local/bin/koc-run-python
      networkEgressPolicy: DENY_ALL
      inputSchemaRef: sandbox-tools/schemas/generated-code-input-v1.json
      outputSchemaRef: sandbox-tools/schemas/generated-code-result-v1.json
      resources: {cpu: 500m, memory: 512Mi, ephemeralStorage: 512Mi, inputMaxBytes: 52428800, outputMaxBytes: 1048576, logMaxBytes: 2097152, scriptMaxBytes: 262144, timeoutSeconds: 120, maxTimeoutSeconds: 300}
    - id: generated-posix-shell
      version: v1
      mode: GENERATED_CODE
      enabled: true
      image:
        repository: ${registry_prefix}/kubeoncall-sandbox-generated-posix-shell
        digest: ${shell_digest}
      entrypoint: /usr/local/bin/koc-run-posix-shell
      networkEgressPolicy: DENY_ALL
      inputSchemaRef: sandbox-tools/schemas/generated-code-input-v1.json
      outputSchemaRef: sandbox-tools/schemas/generated-code-result-v1.json
      resources: {cpu: 500m, memory: 512Mi, ephemeralStorage: 512Mi, inputMaxBytes: 52428800, outputMaxBytes: 1048576, logMaxBytes: 2097152, scriptMaxBytes: 262144, timeoutSeconds: 120, maxTimeoutSeconds: 300}
    - id: manifest-validation
      version: v1
      mode: MANIFEST_VALIDATION
      enabled: true
      image:
        repository: ${registry_prefix}/kubeoncall-sandbox-manifest-validation
        digest: ${manifest_digest}
      entrypoint: /usr/local/bin/koc-validate-manifest
      networkEgressPolicy: DENY_ALL
      inputSchemaRef: sandbox-tools/schemas/manifest-validation-input-v1.json
      outputSchemaRef: sandbox-tools/schemas/manifest-validation-result-v1.json
      resources: {cpu: 500m, memory: 512Mi, ephemeralStorage: 1Gi, inputMaxBytes: 52428800, outputMaxBytes: 1048576, logMaxBytes: 2097152, scriptMaxBytes: 262144, timeoutSeconds: 180, maxTimeoutSeconds: 300}
EOF

echo "rendered ${output_file}"
